---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Thomas Ludwig.
--- DateTime: 30.04.2023 22:00
---

local config = require("config")
local wiredModem = peripheral.wrap("bottom")
local wirelessModem = peripheral.wrap("right")
local remotePort = config["wirelessPort"]+1

term.write("Elevator OS 1.0 - Access Point")

function modemReceive(event, modemSide, senderChannel, replyChannel, message, senderDistance)
    if (tonumber(senderChannel) ~= config["wirelessPort"]) then
        return
    end

    if message == 'reboot' then
        wirelessModem.transmit(remotePort, remotePort, "reboot")
        os.reboot()
    end

    wiredModem.transmit(config["wirelessPort"], replyChannel, message)
end

wirelessModem.open(config["wirelessPort"])
wiredModem.open(config["wirelessPort"])

while true do
    local event, param1, param2, param3, param4, param5 = os.pullEvent()

    if(event == "modem_message") then
        modemReceive(event, param1, param2, param3, param4, param5)
    end
end