---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Thomas Ludwig.
--- DateTime: 30.04.2023 23:49
---

return {
    displays = {"monitor_1","monitor_2","monitor_0","monitor_4","monitor_3","monitor_5"},
    sensors = {"minecraft:dropper_21","minecraft:dropper_20","minecraft:dropper_19","minecraft:dropper_26","minecraft:dropper_13","minecraft:dropper_27"},
    labels = {"Floor","ME Core","Train","Power","Top","Exit"},
    name = "elevator_1",
    upSensor = "minecraft:dropper_24",
    downSensor = "minecraft:dropper_25",
    clutchOut = "computer_10",
    gearOut = "computer_9"
}