---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Thomas Ludwig.
--- DateTime: 07.05.2023 02:35
---
---
local config = require("config")

peripheral.call("left", "open", config["wirelessPort"])

peripheral.call("left", "transmit", config["wirelessPort"], 1, 3)