---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Thomas Ludwig.
--- DateTime: 30.04.2023 22:00
---

local config = require("config")
local displays = config["displays"]
local name = config["name"]

term.write("Elevator OS 1.0 - Touch")

function touchMonitor()
    event, side, xPos, yPos = os.pullEvent("monitor_touch")

    for index = 1, #(displays) do
        local id = displays[index]

        if side == id then
            rs.setAnalogueOutput("left", index)
            os.sleep(1)
            rs.setOutput("left", false)
        end
    end
end

while true do
    touchMonitor()
end